

environment:
  VERSION: 1.3

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

configuration: Release

init:
  - cmd: echo %APPVEYOR_REPO_TAG%
  - cmd: set BUILD_VERSION=%VERSION%.%APPVEYOR_BUILD_NUMBER%
  - cmd: echo %APPVEYOR_REPO_BRANCH%
  - cmd: IF "%APPVEYOR_REPO_TAG%" == "true" (set PROJECT_VERSION=%APPVEYOR_REPO_TAG_NAME%) ELSE (IF "%APPVEYOR_REPO_BRANCH%"=="master" (set PROJECT_VERSION=%BUILD_VERSION%) ELSE (IF "%APPVEYOR_REPO_BRANCH%"=="development" (set PROJECT_VERSION=%BUILD_VERSION%-dev) ELSE (set PROJECT_VERSION=%BUILD_VERSION%-pr)))
  - cmd: echo %PROJECT_VERSION%
  - cmd: echo %APPVEYOR_BUILD_NUMBER%
  - cmd: echo %APPVEYOR_BUILD_VERSION%
  - cmd: echo %APPVEYOR_REPO_TAG_NAME%

install:
  appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

dotnet_csproj:  
  patch: true
  file: '**\*.csproj'
  version: $(PROJECT_VERSION)
  assembly_version: $(VERSION)
  file_version: $(BUILD_VERSION)
  informational_version: $(PROJECT_VERSION)

nuget:
  disable_publish_on_pr: true

before_build:
- cmd: nuget restore

build:
  publish_nuget: true
  verbosity: minimal

deploy:
- provider: NuGet
  api_key:
    secure: J1cupNSUS0zAEqawYeK8+AyqjXYMqemdUVtdOs4jCxMiOMStMaP1TFTnDIcV8kpj
  on:
    APPVEYOR_REPO_TAG: true
